server:
  port: 8088

spring:
  application:
    name: pagoservicios-pagos
  config:
    import: optional:configserver:http://${HOST_API_CONFIGSERVER}:8888
#  r2dbc:
#    url: r2dbc:pool:mssql://${HOST_SQL_SERVER}:1433/BDPAGOSERVICIOS
#    username: sa
#    password: B00tcamp2022
#logging:
#  level:
#    org.springframework.data.r2dbc: DEBUG