server:
  port: 8085

spring:
  application:
    name: pagoservicios-favoritos
  config:
        import: optional:configserver:http://${apiconfigserver}:8888
  data:
      mongodb:
        host: ${mongodb_server}
        port: 27017
        database: favoritos
