server:
  port: 8088

spring:
  config:
        import: optional:configserver:http://${apiconfigserver}:8888
  r2dbc:
        url: r2dbc:pool:mssql://${sql_server}:1433/BDPAGOSERVICIOS
        username: sa
        password: B00tcamp2022
logging:
  level:
      org.springframework.data.r2dbc: DEBUG