server:
  port: 8083

spring:
  config:
        import: optional:configserver:http://${apiconfigserver}:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: rhttp://${keycloak}:8080/auth/realms/Reto-Integrador-Realm
application:
  urlApiFavoritos: http://${apifavoritos}:8085/favoritos
  urlApiPagos: http://${apipagos}:8088/pagos
  urlApiServicios: http://${apipagos}:8088/servicios