server:
  port: 8085

spring:
  application:
    name: pagoservicios-favoritos
  config:
        import: ${HOST_API_CONFIGSERVER}
  data:
      mongodb:
        host: ${HOST_MONGODB_SERVER}
        port: 27017
        database: favoritos
