server:
  port: 8083

spring:
  application:
    name: pagoservicios-servicioux
  config:
        import: ${HOST_API_CONFIGSERVER}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${HOST_KEYCLOAK}
application:
  urlApiFavoritos: ${HOST_API_FAVORITOS}/favoritos
  urlApiPagos: ${HOST_API_PAGOS}/pagos
  urlApiServicios: ${HOST_API_PAGOS}/servicios