server:
  port: 8088

spring:
  application:
    name: pagoservicios-pagos
  config:
        import: ${HOST_API_CONFIGSERVER}
  r2dbc:
        url: ${HOST_SQL_SERVER}
        username: sa
        password: B00tcamp2022
logging:
  level:
      org.springframework.data.r2dbc: DEBUG