server:
  port: 8088

spring:
  application:
    name: pagoservicios-pagos
  config:
    import: optional:configserver:http://${HOST_API_CONFIGSERVER}:8888
  r2dbc:
    url: r2dbc:pool:mssql://${HOST_MYSQL_SERVER}:1433/BDPAGOSERVICIOS
    username: root
    password: toor
logging:
  level:
    org.springframework.data.r2dbc: DEBUG